---
- name: Setup users
  user: name="{{ item.name }}"
        group="{{ item.groups[0] }}"
        groups="{{ item.groups | join(',') }}"
        password="{{ sudoer_passwords[item.name] | default(None) }}"
        state=present
        shell=/bin/bash
        update_password=always
  with_items: users

- name: Add web user sudoers items for services
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ web_user }}-services"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: web_sudoers

- name: Add SSH keys
  authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}"
  with_subelements:
    - users | default([])
    - keys
